name: boiler_plate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  firebase_messaging: ^10.0.4
  firebase_dynamic_links: ^2.0.2
  firebase_analytics: ^8.0.3
  flutter_facebook_auth: ^3.3.3+1
  flutter_twitter_login: ^1.1.0
  the_apple_sign_in: ^1.1.1
  get: ^4.1.4
  get_storage: ^2.0.2
  github_sign_in: ^0.0.3
  google_sign_in: ^5.0.2
  sqflite: ^2.0.0+3
  uuid: ^3.0.4
  firebase_crashlytics: ^2.0.5
  google_fonts: ^2.1.0
  super_text: ^0.1.1
  firebase_storage: ^10.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/secrets/
    - assets/locales/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Italic.ttf
  #         style: italic
